### ISSUE TITLE
Local web app not working - any request to /api/accounts results in 500 error

### ISSUE THREAD

**Issue by muttoni** [onflow/freshmint#16] opened 2022-01-10 10:57 UTC
**Steps to reproduce**

- Create freshmint project
- Follow generated project README (all prior steps worked successfully), all the way to line 119 (launching the web app using `npm run dev`)
- Clicking any button on the web app makes it dim slightly (as if FCL were trying to load the wallet discovery iframe) but nothing happens. Instead the console shows a 500 fetch error to `http://localhost:8701/api/accounts`. 

**System Info**
- macOS 12.0.1
- Node 16.13.1
- Flow CLI versions 0.30.0 and 0.30.2 (restarted docker environment on both attempts)

**Comment by muttoni** [comment] 2022-01-11 09:35
Not really relevant, but just thought I would mention that I was following the tutorial with a custom CSV and image assets to replicate a real user. Here are the assets (just 10 playing cards):

[nfts.csv](https://github.com/onflow/freshmint/files/7845327/nfts.csv)
[images.zip](https://github.com/onflow/freshmint/files/7845331/images.zip)

**Comment by iamjabour** [comment] 2022-01-12 05:56
same here. Workaround is to start flow emulator localy (or inside docker) with support to the dev-wallet: I use `flow project start-emulator ./flow.json --dev-wallet`

**Comment by muttoni** [comment] 2022-01-13 10:14
> flow project start-emulator ./flow.json --dev-wallet

Yes that fixed it for me as well. BTW, I'm also facing the same issue on Kitty items (referenced above), and the same fix solves it. I was able to triage as being an issue with the dev wallet container image (see [here](https://github.com/onflow/kitty-items/issues/189) for log output). The default kitty items dev wallet docker image errors out during any form of wallet discovery with the following error: 

```TX:ERROR execution error code 1101: [Error Code: 1101] cadence runtime error Execution failed:

error: [Error Code: 1054] location (undefined) is not a valid location: expecting an AddressLocation, but other location types are passed
```

@iamjabour can you see if you are able to replicate as well?

**Comment by iamjabour** [comment] 2022-01-13 20:01
No, sorry I'm not using the Kitty items project.

 As far as I could understand of the error: Seems like the docker image for the wallet project has some hardcoded or config setting up at port 300 and is not reading the port from the config. Seems like this is the issue, but I could be wrong.

Cheers,
Iam

**Comment by psiemens** [comment] 2022-04-29 16:50
This is a dev wallet bug and therefore a duplicate of https://github.com/onflow/kitty-items/issues/189, which has been fixed. Thanks for reporting!

**Closed by psiemens** 2022-04-29 16:50 UTC
